"""Akash Kishor Shinde profile: biography and portrait supplied by the user."""
def build_profile(button,link):
 return '''<article class="akash-profile">
<section class="wrap profile-hero">
 <div class="profile-heading"><span class="eyebrow red">About Akash Shinde</span><h1>AKASH KISHOR<br>SHINDE</h1><p class="profile-subtitle">Martial Arts With a Mission</p></div>
 <figure class="profile-portrait"><img src="assets/akash-kishor-shinde.webp" width="720" height="960" alt="Akash Kishor Shinde practising martial arts outdoors in a white uniform and black belt" fetchpriority="high"><figcaption>Akash Kishor Shinde · Mumbai</figcaption></figure>
 <div class="profile-lede"><p>Akash Kishor Shinde is a Mumbai-based martial arts practitioner, karate trainer, and social worker dedicated to making martial arts training accessible to children regardless of their financial background.</p><p>For Akash Shinde, martial arts is not simply about learning how to fight. It is about developing discipline, confidence, fitness, self-defence skills, respect, and a stronger mindset.</p><div class="profile-training-mark"><strong>Free Karate Training.</strong><span>No Paid Classes. No Training Fees.</span></div>'''+link('Discover the mission','#mission')+'''</div>
</section>
<nav class="profile-jump wrap" aria-label="About Akash Shinde sections"><a href="#mission">The mission</a><a href="#training-centres">Free training</a><a href="#journey">The journey</a><a href="#recognition">Recognition</a><a href="#vision">Our vision</a></nav>
<section class="profile-mission" id="mission"><div class="wrap"><span class="eyebrow">His mission is simple</span><blockquote>No child should be denied the opportunity to learn martial arts because they cannot afford the fees.</blockquote><p>That is why the karate training conducted by Akash Shinde is completely free of charge. There are no paid classes and no training fees.</p></div></section>
<section class="wrap section profile-centres" id="training-centres"><div class="profile-section-title"><span class="eyebrow red">Access without barriers</span><h2>FREE KARATE<br>TRAINING IN MUMBAI.</h2><p>Akash Shinde currently provides free karate and martial arts training at two locations in Mumbai.</p></div><div class="profile-location-list"><article><span class="eyebrow">Dharavi</span><h3>Ganesh Vidyamandir School, Dharavi</h3><p>Free karate training for children and students in and around Dharavi.</p><span class="free-label">No training fees</span></article><article><span class="eyebrow">Pratiksha Nagar</span><h3>Pratiksha Nagar, Mumbai</h3><p>A second training centre serving children from Pratiksha Nagar and surrounding communities.</p><span class="free-label">No training fees</span></article><p class="profile-detail-note">Students are trained without charging regular coaching or tuition fees. The objective is to give children access to structured martial arts education that might otherwise be financially out of reach.</p>'''+link('Enquire about training','contact.html?enquiry=regular-classes#contact-enquiry')+'''</div></section>
<section class="profile-values"><div class="wrap section profile-two-column"><div><span class="eyebrow red">More Than Karate</span><h2>LESSONS THAT<br>GO BEYOND THE MAT.</h2><p>The purpose of the training goes beyond kicks, punches, forms, and competition.</p><p>Through regular practice, students are encouraged to develop:</p></div><div><ul class="profile-values-list"><li>Self-discipline and confidence</li><li>Physical fitness and coordination</li><li>Practical self-defence awareness</li><li>Focus and mental strength</li><li>Respect for teachers, parents, and fellow students</li><li>Sportsmanship and teamwork</li><li>The confidence to participate in competitive martial arts</li></ul><p>Akash Shinde believes that the values learned through martial arts can have an impact far beyond the training ground.</p></div></div></section>
<section class="wrap section profile-two-column" id="journey"><div><span class="eyebrow red">A Journey in Martial Arts</span><h2>PRACTITIONER.<br>COMPETITOR.<br>TRAINER. ORGANIZER.</h2></div><div class="profile-prose"><p>Akash Kishor Shinde has been associated with martial arts for many years as a practitioner, competitor, trainer, and organizer.</p><p>The certificates and records documenting his journey include participation and recognition connected with karate and martial-arts competitions dating back several years.</p><p>Among the material documenting his martial-arts journey are records relating to the Mumbai Zonal Inter School TEBMA Martial Arts Championship 2016–17, the 23rd WFSKO Open Asian/International Karate Championship in 2018, and subsequent martial-arts and sports recognition.</p><p>His work and achievements have also appeared in Marathi and Hindi newspapers.</p></div></section>
<section class="profile-recognition" id="recognition"><div class="wrap section"><div class="profile-section-title"><span class="eyebrow">Recognition & Awards</span><h2>A JOURNEY<br>RECOGNIZED.</h2><p>Over the years, Akash Shinde’s martial-arts activities and community work have received recognition from different organizations.</p><p>The documents and press coverage associated with his journey include recognition connected with:</p></div><div class="recognition-list"><article><span class="recognition-year">2019</span><div><h3>Indian Sports Award – 2019</h3><p>Akash Kishor Shinde was documented in the karate category in materials relating to the Indian Sports Award 2019.</p></div></article><article><span class="recognition-year recognition-discipline">KARATE</span><div><h3>Martial Arts & Sports Recognition</h3><p>His certificates document participation and achievements in karate competitions and martial-arts events.</p></div></article><article><span class="recognition-year">2022</span><div><h3>Bharat Bhushan Samman – 2022</h3><p>Multiple newspaper clippings document Akash Shinde receiving the Bharat Bhushan Samman in recognition of his activities and social contribution.</p></div></article></div><p class="recognition-press">His work has also been covered by publications including Marathi and Hindi newspapers, highlighting both his martial-arts activities and his efforts to provide training to children.</p></div></section>
<section class="wrap section profile-two-column"><div><span class="eyebrow red">Giving Children an Opportunity</span><h2>THE MOST IMPORTANT<br>PART IS THE STUDENTS.</h2></div><div class="profile-prose"><p>The most important part of Akash Shinde’s work is not an award or certificate.</p><p><strong>It is the students.</strong></p><p>Through his free classes in Dharavi and Pratiksha Nagar, he aims to create an environment where children can train consistently, learn discipline, improve their fitness, discover their abilities, and build confidence without their family’s financial situation becoming a barrier.</p><p>The goal is not simply to create karate competitors.</p><p>It is to help develop stronger, more disciplined and more confident young people.</p></div></section>
<section class="wrap profile-purpose" id="vision"><article><span class="eyebrow red">Our Mission</span><h2>OPPORTUNITY<br>FOR EVERY CHILD.</h2><p>To provide quality martial arts and karate training completely free of charge to children and young people, particularly those who may otherwise not have access to professional training.</p></article><article><span class="eyebrow red">Our Vision</span><h2>MORE COMMUNITIES.<br>MORE POSSIBILITIES.</h2><p>To expand free martial-arts education to more communities and give more children an opportunity to learn karate, self-defence, discipline and sportsmanship in a safe and supportive environment.</p></article></section>
<section class="trial-band profile-closing"><div class="wrap trial-band-inner"><div><span class="eyebrow">Dharavi · Pratiksha Nagar · Mumbai</span><h2>TRAIN. LEARN. GROW.</h2><p>Free Karate Training. No Paid Classes.</p></div>'''+button('Enquire about free training','contact.html?enquiry=regular-classes#contact-enquiry')+'''</div></section>
</article>'''
