from pathlib import Path
from html import escape as esc
import json
ROOT=Path(__file__).resolve().parents[1]

def build_events(button,link):
 data=json.loads((ROOT/'tools/events-manifest.json').read_text())
 items={x['id']:x for x in data['items']}
 def image(key,eager=False):
  i=items[key]
  return f'<img src="{i["image"]}" alt="{esc(i["alt"])}" width="{i["width"]}" height="{i["height"]}" '+('fetchpriority="high"' if eager else 'loading="lazy"')+' decoding="async">'
 photos=[]
 for i in data['items']:
  photos.append(f'''<figure class="event-photo {'event-panorama' if i['width']/i['height']>2.5 else ''}"><a href="{i['original']}" data-event-open data-title="{esc(i['title'])}" aria-label="Enlarge: {esc(i['title'])}">{image(i['id'])}<span class="event-enlarge" aria-hidden="true">↗</span></a><figcaption>{esc(i['title'])}</figcaption></figure>''')
 activities=[('Belt Grading & Level-Ups','A chance to demonstrate dedication, technique and progress. Students are assessed for belt advancement; moving to the next level depends on meeting the grading requirements.'),('Tournaments & Competitions','Supervised sparring and kata competitions give students a constructive setting to test their techniques, develop composure and practise a healthy competitive spirit.'),('Awards & Prize Distribution','Trophies, medals and certificates celebrate top performers and dedicated students, recognising effort and giving young practitioners encouragement to keep improving.'),('Real-World Self-Defense','Practical self-defense training develops awareness, avoidance, control and appropriate responses. The focus is on making safer decisions and seeking help—not a guarantee of protection in every situation.'),('Personal Growth & Discipline','Beyond physical practice, camp encourages focus, resilience, leadership and respect. Students learn to take responsibility, support one another and build confidence through consistent effort.')]
 activity_html=''.join(f'<details {"open" if n==0 else ""}><summary>{esc(title)}</summary><p>{copy}</p></details>' for n,(title,copy) in enumerate(activities))
 return f'''<article class="events-content">
 <section class="wrap events-hero"><div class="events-hero-copy"><span class="eyebrow red">Royal Sports Academy</span><h1>Events &amp;<br>Karate Camps.</h1><p class="events-lead">More time to practise.<br>More room to grow.</p><p>Twice a year, we bring our students together for an immersive martial arts experience beyond their regular routines—building skill, discipline and confidence on and off the mat.</p><a class="button black" href="#signature-camps">Explore our camps <span aria-hidden="true">↓</span></a></div><figure class="events-hero-photo">{image('event-06',True)}<figcaption>Young practitioners and the people supporting their journey.<span>From the academy archive</span></figcaption></figure></section>
 <nav class="events-section-nav wrap" aria-label="On this page"><a href="#signature-camps">Summer &amp; Winter Camps <span aria-hidden="true">↓</span></a><a href="#camp-activities">Camp Activities <span aria-hidden="true">↓</span></a><a href="#event-gallery">Photo Gallery <span aria-hidden="true">↓</span></a><a href="#camp-enrollment">Enrollment <span aria-hidden="true">↓</span></a></nav>
 <section class="events-camps" id="signature-camps"><div class="wrap section"><div class="events-section-heading"><div><span class="eyebrow">Our signature camps</span><h2>Our seasonal camps.</h2></div><p>An opportunity to step away from the usual routine and give focused time to training, teamwork and personal growth.</p></div><div class="events-season-grid"><article class="events-season"><span class="events-season-label">Summer break</span><h3>Summer Karate Camp</h3><p>A high-energy program designed to keep kids active, focused and disciplined during their summer break.</p><p class="events-season-focus">Movement · Focus · Consistent practice</p><a href="#camp-enrollment">Summer enrollment information <span aria-hidden="true">↗</span></a></article><article class="events-season"><span class="events-season-label">Year-end training</span><h3>Winter Karate Camp</h3><p>An intensive training retreat aimed at sharpening skills, building endurance and finishing the year with renewed confidence.</p><p class="events-season-focus">Technique · Endurance · Continued progress</p><a href="#camp-enrollment">Winter enrollment information <span aria-hidden="true">↗</span></a></article></div><p class="events-season-note">Enrollments open one month before each season. Dates, venue and participation details for the next camp are yet to be announced.</p></div></section>
 <section class="wrap section events-activities" id="camp-activities"><div class="events-activities-intro"><span class="eyebrow red">Camp highlights &amp; activities</span><h2>What happens<br>at camp.</h2><p>Purposeful practice, healthy competition and recognition for the work students put in.</p><figure>{image('event-02')}<figcaption>Certificates, medals and shared progress.<br>Academy archive photograph; season not specified.</figcaption></figure></div><div class="events-activity-list">{activity_html}</div></section>
 <section class="events-gallery-section" id="event-gallery"><div class="wrap section"><div class="events-section-heading"><div><span class="eyebrow red">From the academy archive</span><h2>Event photo gallery.</h2></div><p>Photographs supplied by Royal Sports Academy. Explore the full frames from gatherings, presentations and moments together.</p></div><div class="events-gallery">{''.join(photos)}</div><p class="events-photo-note">{data['input_count']} supplied files · {data['unique_count']} unique photographs. One exact duplicate is shown once; different views of the same gathering are retained. Original image quality varies. Photographs are not assigned to a particular camp season or date.</p></div></section>
 <section class="wrap section events-enrollment" id="camp-enrollment"><div><span class="eyebrow red">Enrollment</span><h2>Join the next camp.</h2><p>Ready to develop your skills? Join us at the next Royal Sports Academy camp and continue your martial arts journey.</p>{button('Enquire about camps','contact.html','black')}</div><div class="events-enrollment-info"><h3>Enrollment information</h3><dl><div><dt>When to enquire</dt><dd>Enrollments open one month before each summer and winter season.</dd></div><div><dt>Next camp details</dt><dd>Exact dates, venue, age eligibility and arrangements will be confirmed by the academy.</dd></div><div><dt>Before attending</dt><dd>A parent or guardian should confirm suitability and participation details for a child. Enquiring does not reserve a place.</dd></div></dl><p class="events-preview-note">This preview is not connected to live camp registration. Regular karate training is free; camp-specific arrangements should be confirmed with the academy.</p></div></section>
 </article>'''+VIEWER

VIEWER='''<dialog id="event-viewer" aria-labelledby="event-viewer-title"><div class="event-viewer-head"><div><span class="eyebrow">Royal Sports Academy / Photo archive</span><h2 id="event-viewer-title">Event photograph</h2></div><button type="button" class="icon-button" data-event-close aria-label="Close photograph">×</button></div><div class="event-viewer-stage"><img id="event-full" alt=""></div><div class="event-viewer-controls"><button type="button" data-event-prev aria-label="Previous photograph">← Previous</button><span id="event-position" role="status"></span><button type="button" data-event-next aria-label="Next photograph">Next →</button><a id="event-original" href="#event-gallery" target="_blank" rel="noopener">Open original ↗</a></div><p class="event-viewer-note">Academy-supplied photograph · Full original frame · Image quality varies.</p></dialog><script src="events.js" defer></script>'''
