"""Coach-led homepage. Real people, clear programmes, no stock hero."""
from pathlib import Path
from html import escape
import json
ROOT=Path(__file__).resolve().parents[1]


def build_home(button, link):
    manifest=json.loads((ROOT/'tools/coaches-manifest.json').read_text(encoding='utf-8'))
    coaches=''
    for person in manifest['items']:
        name=escape(person['name']); language=' lang="mr"' if name=='साहिल हेगडकर' else ''
        coaches+=f'''<article class="coach-card"><figure class="coach-photo"><img src="{person['display']}" width="{person['width']}" height="{person['height']}" loading="lazy" alt="{name} — coach at Royal Sports Academy"></figure><div class="coach-caption"><h3 class="coach-name"{language}>{name}</h3><p>Coach</p></div></article>'''
    tabs=''
    for key,title,note in [('kids','Kids karate','Confidence from the start'),('teens','Teen karate','Focus and steady progress'),('adults','Adult karate','Fitness with purpose'),('sport','Sport karate','Kata and kumite')]:
        selected='true' if key=='kids' else 'false'; tabindex='0' if key=='kids' else '-1'
        tabs+=f'''<button class="program-tab" id="tab-{key}" role="tab" aria-selected="{selected}" aria-controls="program-panel" tabindex="{tabindex}" data-program="{key}"><span><span class="tab-title">{title}</span><span class="tab-note">{note}</span></span><span class="tab-arrow" aria-hidden="true">↗</span></button>'''
    return '''<section class="hero home-hero"><div class="wrap r-hero-grid"><div class="r-hero-copy"><span class="eyebrow">Royal Karate Sports · Mumbai</span><h1>Train with<br><span>Akash Shinde.</span></h1><p class="hero-subtitle">Free karate training. Personal guidance.<br>A stronger, more confident you.</p><p class="r-hero-description">Learn karate with the founder and head coach of Royal Sports Academy, in Dharavi and Pratiksha Nagar.</p><div class="actions">'''+button('Contact the academy','contact.html?enquiry=regular-classes#contact-enquiry')+link('Explore programmes','#programmes')+'''</div><div class="r-hero-note">No paid regular classes. No training fees.</div></div><figure class="r-hero-portrait"><img src="assets/akash-kishor-shinde.webp" width="720" height="960" alt="Akash Kishor Shinde practising martial arts outdoors in a white uniform" fetchpriority="high"><figcaption><span>Founder &amp; Head Coach</span><strong>Akash Kishor Shinde</strong></figcaption></figure></div></section>
<section class="section r-programmes" id="programmes"><div class="wrap"><div class="r-section-heading"><div><span class="eyebrow">Find your class</span><h2>Karate at your<br>stage of life.</h2></div><p>Starting out or returning to practice? Explore the programmes, then speak with the academy about the right group for you.</p></div><div class="program-layout"><div class="program-tabs" role="tablist" aria-label="Karate programs" aria-orientation="vertical">'''+tabs+'''</div><div id="program-panel" role="tabpanel" aria-labelledby="tab-kids" tabindex="0"><div class="program-visual"><img id="program-image" src="assets/kids-group-training.webp" width="554" height="554" loading="lazy" alt="Young karate students practising stances together on blue and red mats"></div><div class="program-copy"><div><span id="program-tag">Kids · Foundations</span><p id="program-description">Personal attention, karate basics and fitness training to help young learners develop concentration, confidence and coordination.</p></div>'''+link('Programme details','programs.html#kids').replace('class="text-link"','class="text-link" id="program-link"')+'''</div></div></div></div></section>
<section class="home-access section" id="academy"><div class="wrap r-community-grid"><figure><img src="assets/royal-academy-group.webp" width="960" height="720" loading="lazy" alt="Academy group photograph with students holding certificates and medals"><figcaption>From the Royal Sports Academy photo archive</figcaption></figure><div><span class="eyebrow">Our academy</span><h2>Good training should<br>be open to everyone.</h2><p>For Akash Kishor Shinde, karate is about more than technique. It is a way to build discipline, confidence and opportunity—without a family's income becoming a barrier.</p><p>Regular karate training is completely <strong>free of charge</strong>.</p><div class="r-centres"><div><strong>Dharavi</strong><span>Ganesh Vidyamandir School</span></div><div><strong>Pratiksha Nagar</strong><span>Mumbai</span></div></div>'''+link('About the academy','academy.html')+'''<p class="small">Confirm current class timings and meeting instructions before visiting.</p></div></div></section>
<section class="home-team section" id="our-team" aria-labelledby="team-title"><div class="wrap"><header class="r-section-heading team-heading"><div><span class="eyebrow">The coaching team</span><h2 id="team-title">Led by Akash.<br>Supported by our coaches.</h2></div><div><p>Akash Kishor Shinde is the academy’s founder and head coach. Meet the other coaches at Royal Sports Academy.</p>'''+link('Meet our head coach','about-akash-shinde.html')+'''</div></header><div class="coaches-grid">'''+coaches+'''</div></div></section>
<section class="home-camps section" id="home-camps"><div class="wrap r-camp-layout"><div class="r-camp-copy"><span class="eyebrow">Beyond regular classes</span><h2>Train together.<br>Grow together.</h2><p>Summer and winter camps take place twice a year, with more time for practice, shared challenges and personal growth.</p><p>Belt grading, kata &amp; sparring, awards and practical self-defense are part of the camp activities.</p><p class="small">Enrollment begins one month before each season. Confirm dates, venue and availability with the academy.</p>'''+button('Explore camps & events','events.html','black')+'''</div><figure><img src="assets/events/event-02.webp" width="544" height="183" loading="lazy" alt="Karate practitioners on mats holding certificates and wearing medals"><figcaption>Training and shared progress, from the academy archive.</figcaption><div class="r-archive-links">'''+link('Achievements & recognition','achievements.html')+link('Read the press archive','media.html')+'''</div></figure></div></section>
<section class="wrap section home-faq"><div><span class="eyebrow">Before you begin</span><h2>Your first class,<br>made clearer.</h2>'''+link('Ask the academy','contact.html')+'''</div><div class="faq-list"><details><summary>Is regular karate training really free?</summary><p>Yes. Regular karate training conducted by Akash Kishor Shinde is completely free of charge, with no paid classes and no training fees.</p></details><details><summary>Where can I train?</summary><p>Training is held at Ganesh Vidyamandir School, Dharavi, and Pratiksha Nagar, Mumbai. Confirm the current timetable, exact meeting point and availability before attending.</p></details><details><summary>When can I enroll for a camp?</summary><p>Summer and winter camps are held twice a year. Enrollment begins one month before each season. Confirm dates, venue and availability with the academy; no current opening is announced here.</p></details><details><summary>Can I start without experience?</summary><p>Yes, you can enquire as a beginner. A parent or guardian should enquire for a child and confirm age suitability, supervision and what to bring before attending.</p></details></div></section>'''

if __name__=='__main__':
    import runpy
    runpy.run_path(str(ROOT/'tools/build.py'),run_name='__main__')
