from pathlib import Path
from html import escape
import json
ROOT=Path(__file__).resolve().parents[1]
CATEGORIES={'press':'Press coverage','records':'Letters & records'}

def build_media(button,link):
    data=json.loads((ROOT/'tools/media-manifest.json').read_text(encoding='utf-8'))
    labels=json.loads((ROOT/'tools/media-labels.json').read_text(encoding='utf-8'))
    assert set(labels)=={x['id'] for x in data['items']}
    figures=[]
    for item in data['items']:
        meta=labels[item['id']];title=escape(meta['title']);alt=escape(meta['alt']);category=meta['category']
        figures.append(f'''<figure data-media-category="{category}" id="{item['id']}"><a class="press-scan" href="{item['original']}" data-press-open data-title="{title}" aria-label="Read: {title}"><img src="{item['thumbnail']}" alt="{alt}" width="{item['width']}" height="{item['height']}" loading="lazy" decoding="async"><span class="press-open-label">View full document <span aria-hidden="true">↗</span></span></a><figcaption><span>{CATEGORIES[category]}</span><h3>{title}</h3></figcaption></figure>''')
    return '''<article class="media-content">
<section class="wrap media-intro"><div><span class="eyebrow red">Trending / Media &amp; Press</span><h1>Our Journey in the Spotlight.</h1><p class="media-subtitle">Royal Sports Academy · Akash Kishor Shinde</p><p>The work of Royal Sports Academy and Akash Kishor Shinde has been featured across various newspapers and media publications over the years.</p><p>From karate achievements and sporting events to community initiatives and free training for children, these stories highlight a journey built around sports, discipline, opportunity and social contribution.</p><a class="button black" href="#media-gallery">Explore the media gallery <span aria-hidden="true">↓</span></a></div><figure class="media-feature"><a href="assets/press/press-11.jpg" data-press-open data-title="Navarashtra · Bharat Bhushan coverage" aria-label="Read featured Navarashtra clipping"><img src="assets/press/press-11.webp" alt="Navarashtra newspaper feature on Bharat Bhushan recognition and free karate training" width="771" height="679" fetchpriority="high"><span class="press-open-label">Read the feature <span aria-hidden="true">↗</span></span></a><figcaption>From the supplied archive / Navarashtra</figcaption></figure></section>
<section class="media-gallery-section" id="media-gallery"><div class="wrap section"><div class="media-gallery-heading"><div><span class="eyebrow red">The archive</span><h2>Media Gallery</h2><p>Press Coverage • Newspaper Features • Awards • Events</p></div><p>Explore newspaper clippings, event photographs, recognition records and memorable moments documenting the journey of Royal Sports Academy and Akash Kishor Shinde.</p></div><div class="press-toolbar"><div class="press-filters" role="group" aria-label="Filter media archive"><button type="button" data-media-filter="all" aria-pressed="true">All media</button><button type="button" data-media-filter="press" aria-pressed="false">Press coverage</button><button type="button" data-media-filter="records" aria-pressed="false">Letters &amp; records</button></div><p id="press-count" role="status">'''+str(data['unique_count'])+''' archive items</p></div><p class="media-reading-note">Select a scan to read it. Zoom in or open the original image for small print. Photographs of events appear within several press clippings.</p><div class="press-grid">'''+''.join(figures)+'''</div><p class="media-archive-note">Original scans supplied by the academy; captions describe the visible material. Source quality varies. Duplicate copies are shown once. Documents and press wording are not independent verification of an honour’s official status.</p></div></section>
<section class="wrap section media-featured"><div><span class="eyebrow red">Featured in the Media</span><h2>SPORT. OPPORTUNITY.<br>COMMUNITY.</h2><p>Royal Sports Academy's work has received coverage in Marathi, Hindi and regional news publications, with stories covering Akash Shinde's achievements, awards, karate journey and efforts to make training accessible to children.</p><p>Media coverage has highlighted different milestones, including:</p></div><dl><div><dt>Free Karate Training</dt><dd>Initiatives providing children with karate training without regular coaching fees.</dd></div><div><dt>Sports &amp; Karate Achievements</dt><dd>Participation and recognition across karate competitions and sporting events.</dd></div><div><dt>Awards &amp; Recognition</dt><dd>Coverage of honours and recognitions received from different organizations.</dd></div><div><dt>Community Work</dt><dd>Efforts to use karate and sports to encourage discipline, fitness and confidence among children.</dd></div><div><dt>Royal Sports Academy</dt><dd>Activities, students, events and the academy's continuing community-focused work.</dd></div></dl></section>
<section class="media-purpose"><div class="wrap section media-purpose-inner"><div><span class="eyebrow">In the News</span><h2>Stories That Go Beyond Sports</h2></div><div><p>For Royal Sports Academy, media recognition is not simply about appearing in a newspaper.</p><p>Every story represents the students who train, the people who support the initiative and the belief that financial circumstances should not prevent a child from getting an opportunity to learn.</p><p>The academy continues to provide <strong>100% free karate training, with no paid regular classes</strong>, at:</p><ul><li>Ganesh Vidyamandir School, Dharavi, Mumbai</li><li>Pratiksha Nagar, Mumbai</li></ul>'''+link('About Royal Sports Academy','academy.html')+'''</div></div></section>
<section class="wrap section media-recognition"><div><span class="eyebrow red">Awards &amp; Recognition in the Press</span><h2>THE STORY BEHIND<br>THE RECOGNITION.</h2></div><div><p>Over the years, newspaper reports have documented different stages of Akash Kishor Shinde's sporting and community journey, including karate achievements and recognitions such as the <strong>Indian Sports Award 2019</strong> and <strong>Bharat Bhushan Samman 2022</strong>, among other organizational honours.</p><div class="media-nomination"><h3>Padma Awards 2023 · Nomination record</h3><p>According to the academy's supplied account, his name also appears in the Ministry of Home Affairs' published list of nominations received for the Padma Awards 2023.</p><p><strong>This is a nomination, not receipt of a Padma Award.</strong></p><p class="small">The original Ministry list is not included in this gallery and has not been independently checked for this preview.</p></div>'''+link('Read Akash Shinde’s story','about-akash-shinde.html')+'''</div></section><div class="wrap media-closing"><p>Every feature tells a part of our story.<br>Every achievement inspires us to keep moving forward.</p><a class="text-link" href="#media-gallery">Back to the archive <span aria-hidden="true">↑</span></a></div>
</article>
<dialog id="press-viewer" aria-labelledby="press-viewer-title"><div class="press-viewer-head"><div><span class="eyebrow">Academy media archive</span><h2 id="press-viewer-title">Document</h2></div><button type="button" class="icon-button" data-press-close aria-label="Close document">×</button></div><div class="press-viewer-tools"><button type="button" data-press-prev aria-label="Previous document">← Previous</button><button type="button" data-press-next aria-label="Next document">Next →</button><button type="button" data-press-zoom aria-pressed="false">Zoom in</button><a id="press-original" href="assets/press/press-01.jpg" target="_blank" rel="noopener noreferrer">Open original ↗</a></div><div class="press-image-stage"><img id="press-viewer-image" src="assets/press/press-11.webp" alt=""></div><p id="press-position" aria-live="polite"></p><p class="press-viewer-note">Supplied scan · Original wording preserved · Readability depends on source quality.</p></dialog><script src="media.js" defer></script>'''
