"""Shared shell for the replacement Royal template."""
from html import escape
from categories import navigation, footer_navigation

MARK='<img class="brand-logo" src="assets/brand/royal-logo.png" width="72" height="72" alt="Royal Sports &amp; Martial Arts Academy logo" decoding="async">'
BRAND=f'<a class="brand" href="index.html" aria-label="Royal Karate Sports home">{MARK}<span class="brand-name">ROYAL<small>KARATE SPORTS</small></span></a>'
SOCIAL='''<div class="footer-social"><a href="https://www.instagram.com/royalsportsmartialartsacademy/" target="_blank" rel="noopener noreferrer" aria-label="Instagram"><svg viewBox="0 0 24 24" width="20" height="20" fill="none" aria-hidden="true"><rect x="3" y="3" width="18" height="18" rx="5" stroke="currentColor" stroke-width="1.8"/><circle cx="12" cy="12" r="4" stroke="currentColor" stroke-width="1.8"/><circle cx="17.5" cy="6.5" r="1" fill="currentColor"/></svg></a><a href="https://www.facebook.com/vishal.kadam09/about" target="_blank" rel="noopener noreferrer" aria-label="Facebook"><svg viewBox="0 0 24 24" width="20" height="20" aria-hidden="true"><path fill="currentColor" d="M14.3 22v-9h3l.45-3.5H14.3V7.3c0-1 .3-1.7 1.8-1.7H18V2.5c-.33-.04-1.45-.14-2.75-.14-2.72 0-4.58 1.66-4.58 4.71V9.5H7.6V13h3.07v9z"/></svg></a></div>'''
LIGHTBOX='''<dialog class="lightbox" aria-labelledby="lightbox-title"><div class="lightbox-head"><h2 id="lightbox-title">Training image</h2><button class="icon-button" data-close-lightbox aria-label="Close photo">×</button></div><img src="assets/7045595.webp" alt=""><p class="small">Illustrative stock photography. Not Royal Karate Sports students or premises.</p></dialog>'''


def render_shell(name,title,body,kind=''):
    page_type='r-home' if name=='index.html' else 'r-page'
    description='Free regular karate training in Mumbai, led by founder and head coach Akash Kishor Shinde. Explore Royal Sports Academy programmes, centres and archives.'
    lightbox=LIGHTBOX if name=='gallery.html' else ''
    return f'''<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#142b3c"><title>{escape(title)} | Royal Karate Sports</title><meta name="description" content="{description}"><meta name="robots" content="noindex,nofollow"><link rel="icon" href="assets/brand/favicon.png" type="image/png" sizes="64x64"><link rel="alternate icon" href="assets/brand/favicon.ico"><link rel="apple-touch-icon" href="assets/brand/apple-touch-icon.png" sizes="180x180"><link rel="stylesheet" href="royal.css"><link rel="stylesheet" href="royal-pages.css"><script src="site.js" defer></script></head>
<body class="royal-design {page_type} {kind}"><a class="skip-link" href="#main">Skip to content</a>
<header class="site-header"><div class="wrap header-inner">{BRAND}<nav class="desktop-nav" aria-label="Main navigation">{navigation(name)}</nav><button class="menu-toggle" aria-label="Open navigation" aria-haspopup="dialog" aria-controls="mobile-menu">Menu<span class="hamburger" aria-hidden="true"></span></button></div></header>
<dialog class="mobile-menu" id="mobile-menu" aria-label="Main navigation"><div class="menu-top">{BRAND}<button class="icon-button" data-close-menu aria-label="Close navigation">×</button></div><nav>{navigation(name,mobile=True)}</nav></dialog>
<main id="main">{body}</main>
<footer class="footer"><div class="wrap"><div class="footer-top"><div class="footer-brand">{BRAND}<p>Karate. Confidence. Community.<br>Free regular training in Mumbai.</p><div class="footer-coach"><span>Founder &amp; Head Coach</span><a href="about-akash-shinde.html">Akash Kishor Shinde</a></div></div><div><h3>Explore Royal</h3><nav class="footer-links" aria-label="Footer navigation">{footer_navigation(name)}<a href="locations.html">Training centres</a><a href="gallery.html">Photo gallery</a></nav></div><div class="footer-contact"><h3>Speak with the academy</h3><p>Shree Aakash shinde</p><p><a href="tel:+918898329666">8898329666</a></p><p><a href="mailto:always4u.06@gmail.com">always4u.06@gmail.com</a></p><p>Dharavi &amp; Pratiksha Nagar, Mumbai</p>{SOCIAL}</div></div><div class="footer-bottom"><p>© 2026 Royal Karate Sports</p><div><a href="information.html">Privacy &amp; credits</a><a href="information.html">Local website preview</a></div></div></div></footer>{lightbox}</body></html>'''
